server:
  port: 8085

spring:
  application:
    name: weather
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enable: true
      path: /h2

logging:
  level:
    root: INFO
  format: TEXT
  debug: false

services:
  weather:
    api:
      url: https://api.weatherapi.com/v1/forecast.json